"""

Revision ID: 8e273ea9fe24
Revises: db5c2351e6c1
Create Date: 2025-04-24 16:44:46.457251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e273ea9fe24'
down_revision = 'db5c2351e6c1'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE itemstatus ADD VALUE IF NOT EXISTS 'REVIEWED'")
    op.execute("ALTER TYPE packagestatus ADD VALUE IF NOT EXISTS 'REVIEWED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
