/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as NeedAccessImport } from './routes/need-access'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as ErrorImport } from './routes/error'
import { Route as IndexImport } from './routes/index'
import { Route as OidcCallbackIndexImport } from './routes/oidc-callback/index'
import { Route as StaffNoRolesImport } from './routes/staff/no-roles'
import { Route as StaffStaffLayoutImport } from './routes/staff/_staffLayout'
import { Route as ProponentProponentLayoutImport } from './routes/proponent/_proponentLayout'
import { Route as ProponentRegistrationIndexImport } from './routes/proponent/registration/index'
import { Route as ProponentRegistrationCreateAccountImport } from './routes/proponent/registration/create-account'
import { Route as ProponentRegistrationCompleteImport } from './routes/proponent/registration/complete'
import { Route as ProponentProponentLayoutProfileImport } from './routes/proponent/_proponentLayout/profile'
import { Route as StaffStaffLayoutProjectsIndexImport } from './routes/staff/_staffLayout/projects/index'
import { Route as StaffStaffLayoutInvitationsIndexImport } from './routes/staff/_staffLayout/invitations/index'
import { Route as StaffStaffLayoutDocumentsIndexImport } from './routes/staff/_staffLayout/documents/index'
import { Route as ProponentProponentLayoutUserManagementIndexImport } from './routes/proponent/_proponentLayout/user-management/index'
import { Route as ProponentProponentLayoutProjectsIndexImport } from './routes/proponent/_proponentLayout/projects/index'
import { Route as ProponentProponentLayoutUserManagementUserDetailsImport } from './routes/proponent/_proponentLayout/user-management/user-details'
import { Route as ProponentProponentLayoutUserManagementProfileImport } from './routes/proponent/_proponentLayout/user-management/profile'
import { Route as ProponentProponentLayoutUserManagementNewUserImport } from './routes/proponent/_proponentLayout/user-management/new-user'
import { Route as ProponentProponentLayoutUserManagementEditRoleImport } from './routes/proponent/_proponentLayout/user-management/edit-role'
import { Route as ProponentProponentLayoutUserManagementEditProfileImport } from './routes/proponent/_proponentLayout/user-management/edit-profile'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout'
import { Route as StaffStaffLayoutInvitationsEntitiesProponentIdImport } from './routes/staff/_staffLayout/invitations/entities/$proponentId'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutIndexImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/index'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index'
import { Route as StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport } from './routes/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
import { Route as ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport } from './routes/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'

// Create Virtual Routes

const StaffImport = createFileRoute('/staff')()
const ProponentImport = createFileRoute('/proponent')()
const ProponentProponentLayoutAboutpageLazyImport = createFileRoute(
  '/proponent/_proponentLayout/aboutpage',
)()
const StaffStaffLayoutProjectsProjectIdImport = createFileRoute(
  '/staff/_staffLayout/projects/$projectId',
)()
const ProponentProponentLayoutProjectsProjectIdImport = createFileRoute(
  '/proponent/_proponentLayout/projects/$projectId',
)()
const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport =
  createFileRoute(
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId',
  )()
const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport =
  createFileRoute(
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId',
  )()

// Create/Update Routes

const StaffRoute = StaffImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRoute,
} as any)

const ProponentRoute = ProponentImport.update({
  id: '/proponent',
  path: '/proponent',
  getParentRoute: () => rootRoute,
} as any)

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const NeedAccessRoute = NeedAccessImport.update({
  id: '/need-access',
  path: '/need-access',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OidcCallbackIndexRoute = OidcCallbackIndexImport.update({
  id: '/oidc-callback/',
  path: '/oidc-callback/',
  getParentRoute: () => rootRoute,
} as any)

const StaffNoRolesRoute = StaffNoRolesImport.update({
  id: '/no-roles',
  path: '/no-roles',
  getParentRoute: () => StaffRoute,
} as any)

const StaffStaffLayoutRoute = StaffStaffLayoutImport.update({
  id: '/_staffLayout',
  getParentRoute: () => StaffRoute,
} as any)

const ProponentProponentLayoutRoute = ProponentProponentLayoutImport.update({
  id: '/_proponentLayout',
  getParentRoute: () => ProponentRoute,
} as any)

const ProponentRegistrationIndexRoute = ProponentRegistrationIndexImport.update(
  {
    id: '/registration/',
    path: '/registration/',
    getParentRoute: () => ProponentRoute,
  } as any,
)

const ProponentProponentLayoutAboutpageLazyRoute =
  ProponentProponentLayoutAboutpageLazyImport.update({
    id: '/aboutpage',
    path: '/aboutpage',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any).lazy(() =>
    import('./routes/proponent/_proponentLayout/aboutpage.lazy').then(
      (d) => d.Route,
    ),
  )

const ProponentRegistrationCreateAccountRoute =
  ProponentRegistrationCreateAccountImport.update({
    id: '/registration/create-account',
    path: '/registration/create-account',
    getParentRoute: () => ProponentRoute,
  } as any)

const ProponentRegistrationCompleteRoute =
  ProponentRegistrationCompleteImport.update({
    id: '/registration/complete',
    path: '/registration/complete',
    getParentRoute: () => ProponentRoute,
  } as any)

const ProponentProponentLayoutProfileRoute =
  ProponentProponentLayoutProfileImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const StaffStaffLayoutProjectsProjectIdRoute =
  StaffStaffLayoutProjectsProjectIdImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)

const ProponentProponentLayoutProjectsProjectIdRoute =
  ProponentProponentLayoutProjectsProjectIdImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const StaffStaffLayoutProjectsIndexRoute =
  StaffStaffLayoutProjectsIndexImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)

const StaffStaffLayoutInvitationsIndexRoute =
  StaffStaffLayoutInvitationsIndexImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)

const StaffStaffLayoutDocumentsIndexRoute =
  StaffStaffLayoutDocumentsIndexImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)

const ProponentProponentLayoutUserManagementIndexRoute =
  ProponentProponentLayoutUserManagementIndexImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentProponentLayoutProjectsIndexRoute =
  ProponentProponentLayoutProjectsIndexImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentProponentLayoutUserManagementUserDetailsRoute =
  ProponentProponentLayoutUserManagementUserDetailsImport.update({
    id: '/user-management/user-details',
    path: '/user-management/user-details',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentProponentLayoutUserManagementProfileRoute =
  ProponentProponentLayoutUserManagementProfileImport.update({
    id: '/user-management/profile',
    path: '/user-management/profile',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentProponentLayoutUserManagementNewUserRoute =
  ProponentProponentLayoutUserManagementNewUserImport.update({
    id: '/user-management/new-user',
    path: '/user-management/new-user',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentProponentLayoutUserManagementEditRoleRoute =
  ProponentProponentLayoutUserManagementEditRoleImport.update({
    id: '/user-management/edit-role',
    path: '/user-management/edit-role',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const ProponentProponentLayoutUserManagementEditProfileRoute =
  ProponentProponentLayoutUserManagementEditProfileImport.update({
    id: '/user-management/edit-profile',
    path: '/user-management/edit-profile',
    getParentRoute: () => ProponentProponentLayoutRoute,
  } as any)

const StaffStaffLayoutProjectsProjectIdProjectLayoutRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutImport.update({
    id: '/_projectLayout',
    getParentRoute: () => StaffStaffLayoutProjectsProjectIdRoute,
  } as any)

const StaffStaffLayoutInvitationsEntitiesProponentIdRoute =
  StaffStaffLayoutInvitationsEntitiesProponentIdImport.update({
    id: '/invitations/entities/$proponentId',
    path: '/invitations/entities/$proponentId',
    getParentRoute: () => StaffStaffLayoutRoute,
  } as any)

const ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutImport.update({
    id: '/_projectLayout',
    getParentRoute: () => ProponentProponentLayoutProjectsProjectIdRoute,
  } as any)

const StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StaffStaffLayoutProjectsProjectIdProjectLayoutRoute,
  } as any)

const ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute,
  } as any)

const ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionImport.update(
    {
      id: '/new-submission',
      path: '/new-submission',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport.update(
    {
      id: '/submission-packages/$submissionPackageId',
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () => StaffStaffLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport.update(
    {
      id: '/submission-packages/$submissionPackageId',
      path: '/submission-packages/$submissionPackageId',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport.update(
    {
      id: '/_submissionLayout',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport.update(
    {
      id: '/_submissionLayout',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute,
    } as any,
  )

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport.update(
    {
      id: '/submissions/$submissionId',
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport.update(
    {
      id: '/submissions/$submissionId',
      path: '/submissions/$submissionId',
      getParentRoute: () =>
        ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/need-access': {
      id: '/need-access'
      path: '/need-access'
      fullPath: '/need-access'
      preLoaderRoute: typeof NeedAccessImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
    '/proponent': {
      id: '/proponent'
      path: '/proponent'
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentImport
      parentRoute: typeof rootRoute
    }
    '/proponent/_proponentLayout': {
      id: '/proponent/_proponentLayout'
      path: '/proponent'
      fullPath: '/proponent'
      preLoaderRoute: typeof ProponentProponentLayoutImport
      parentRoute: typeof ProponentRoute
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffImport
      parentRoute: typeof rootRoute
    }
    '/staff/_staffLayout': {
      id: '/staff/_staffLayout'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffStaffLayoutImport
      parentRoute: typeof StaffRoute
    }
    '/staff/no-roles': {
      id: '/staff/no-roles'
      path: '/no-roles'
      fullPath: '/staff/no-roles'
      preLoaderRoute: typeof StaffNoRolesImport
      parentRoute: typeof StaffImport
    }
    '/oidc-callback/': {
      id: '/oidc-callback/'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackIndexImport
      parentRoute: typeof rootRoute
    }
    '/proponent/_proponentLayout/profile': {
      id: '/proponent/_proponentLayout/profile'
      path: '/profile'
      fullPath: '/proponent/profile'
      preLoaderRoute: typeof ProponentProponentLayoutProfileImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/registration/complete': {
      id: '/proponent/registration/complete'
      path: '/registration/complete'
      fullPath: '/proponent/registration/complete'
      preLoaderRoute: typeof ProponentRegistrationCompleteImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/registration/create-account': {
      id: '/proponent/registration/create-account'
      path: '/registration/create-account'
      fullPath: '/proponent/registration/create-account'
      preLoaderRoute: typeof ProponentRegistrationCreateAccountImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/_proponentLayout/aboutpage': {
      id: '/proponent/_proponentLayout/aboutpage'
      path: '/aboutpage'
      fullPath: '/proponent/aboutpage'
      preLoaderRoute: typeof ProponentProponentLayoutAboutpageLazyImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/registration/': {
      id: '/proponent/registration/'
      path: '/registration'
      fullPath: '/proponent/registration'
      preLoaderRoute: typeof ProponentRegistrationIndexImport
      parentRoute: typeof ProponentImport
    }
    '/proponent/_proponentLayout/user-management/edit-profile': {
      id: '/proponent/_proponentLayout/user-management/edit-profile'
      path: '/user-management/edit-profile'
      fullPath: '/proponent/user-management/edit-profile'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementEditProfileImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/user-management/edit-role': {
      id: '/proponent/_proponentLayout/user-management/edit-role'
      path: '/user-management/edit-role'
      fullPath: '/proponent/user-management/edit-role'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementEditRoleImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/user-management/new-user': {
      id: '/proponent/_proponentLayout/user-management/new-user'
      path: '/user-management/new-user'
      fullPath: '/proponent/user-management/new-user'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementNewUserImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/user-management/profile': {
      id: '/proponent/_proponentLayout/user-management/profile'
      path: '/user-management/profile'
      fullPath: '/proponent/user-management/profile'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementProfileImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/user-management/user-details': {
      id: '/proponent/_proponentLayout/user-management/user-details'
      path: '/user-management/user-details'
      fullPath: '/proponent/user-management/user-details'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementUserDetailsImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/projects/': {
      id: '/proponent/_proponentLayout/projects/'
      path: '/projects'
      fullPath: '/proponent/projects'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsIndexImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/user-management/': {
      id: '/proponent/_proponentLayout/user-management/'
      path: '/user-management'
      fullPath: '/proponent/user-management'
      preLoaderRoute: typeof ProponentProponentLayoutUserManagementIndexImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/staff/_staffLayout/documents/': {
      id: '/staff/_staffLayout/documents/'
      path: '/documents'
      fullPath: '/staff/documents'
      preLoaderRoute: typeof StaffStaffLayoutDocumentsIndexImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/staff/_staffLayout/invitations/': {
      id: '/staff/_staffLayout/invitations/'
      path: '/invitations'
      fullPath: '/staff/invitations'
      preLoaderRoute: typeof StaffStaffLayoutInvitationsIndexImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/staff/_staffLayout/projects/': {
      id: '/staff/_staffLayout/projects/'
      path: '/projects'
      fullPath: '/staff/projects'
      preLoaderRoute: typeof StaffStaffLayoutProjectsIndexImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/proponent/_proponentLayout/projects/$projectId': {
      id: '/proponent/_proponentLayout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/proponent/projects/$projectId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdImport
      parentRoute: typeof ProponentProponentLayoutImport
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout'
      path: '/projects/$projectId'
      fullPath: '/proponent/projects/$projectId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdRoute
    }
    '/staff/_staffLayout/invitations/entities/$proponentId': {
      id: '/staff/_staffLayout/invitations/entities/$proponentId'
      path: '/invitations/entities/$proponentId'
      fullPath: '/staff/invitations/entities/$proponentId'
      preLoaderRoute: typeof StaffStaffLayoutInvitationsEntitiesProponentIdImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId': {
      id: '/staff/_staffLayout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/staff/projects/$projectId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdImport
      parentRoute: typeof StaffStaffLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout'
      path: '/projects/$projectId'
      fullPath: '/staff/projects/$projectId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission'
      path: '/new-submission'
      fullPath: '/proponent/projects/$projectId/new-submission'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutImport
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
      path: '/submission-packages/$submissionPackageId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
      path: '/'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport
      parentRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
    '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': {
      id: '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
      preLoaderRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdImport
      parentRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutImport
    }
  }
}

// Create and export the route tree

interface ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren {
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
}

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren: ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren =
  {
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
  }

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute._addFileChildren(
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren,
  )

interface ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren {
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
}

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren: ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren =
  {
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren,
  }

const ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute._addFileChildren(
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren,
  )

interface ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren {
  ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren
}

const ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren: ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren =
  {
    ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute,
    ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute,
    ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren,
  }

const ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren =
  ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute._addFileChildren(
    ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteChildren,
  )

interface ProponentProponentLayoutProjectsProjectIdRouteChildren {
  ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute: typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren
}

const ProponentProponentLayoutProjectsProjectIdRouteChildren: ProponentProponentLayoutProjectsProjectIdRouteChildren =
  {
    ProponentProponentLayoutProjectsProjectIdProjectLayoutRoute:
      ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren,
  }

const ProponentProponentLayoutProjectsProjectIdRouteWithChildren =
  ProponentProponentLayoutProjectsProjectIdRoute._addFileChildren(
    ProponentProponentLayoutProjectsProjectIdRouteChildren,
  )

interface ProponentProponentLayoutRouteChildren {
  ProponentProponentLayoutProfileRoute: typeof ProponentProponentLayoutProfileRoute
  ProponentProponentLayoutAboutpageLazyRoute: typeof ProponentProponentLayoutAboutpageLazyRoute
  ProponentProponentLayoutUserManagementEditProfileRoute: typeof ProponentProponentLayoutUserManagementEditProfileRoute
  ProponentProponentLayoutUserManagementEditRoleRoute: typeof ProponentProponentLayoutUserManagementEditRoleRoute
  ProponentProponentLayoutUserManagementNewUserRoute: typeof ProponentProponentLayoutUserManagementNewUserRoute
  ProponentProponentLayoutUserManagementProfileRoute: typeof ProponentProponentLayoutUserManagementProfileRoute
  ProponentProponentLayoutUserManagementUserDetailsRoute: typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  ProponentProponentLayoutProjectsIndexRoute: typeof ProponentProponentLayoutProjectsIndexRoute
  ProponentProponentLayoutUserManagementIndexRoute: typeof ProponentProponentLayoutUserManagementIndexRoute
  ProponentProponentLayoutProjectsProjectIdRoute: typeof ProponentProponentLayoutProjectsProjectIdRouteWithChildren
}

const ProponentProponentLayoutRouteChildren: ProponentProponentLayoutRouteChildren =
  {
    ProponentProponentLayoutProfileRoute: ProponentProponentLayoutProfileRoute,
    ProponentProponentLayoutAboutpageLazyRoute:
      ProponentProponentLayoutAboutpageLazyRoute,
    ProponentProponentLayoutUserManagementEditProfileRoute:
      ProponentProponentLayoutUserManagementEditProfileRoute,
    ProponentProponentLayoutUserManagementEditRoleRoute:
      ProponentProponentLayoutUserManagementEditRoleRoute,
    ProponentProponentLayoutUserManagementNewUserRoute:
      ProponentProponentLayoutUserManagementNewUserRoute,
    ProponentProponentLayoutUserManagementProfileRoute:
      ProponentProponentLayoutUserManagementProfileRoute,
    ProponentProponentLayoutUserManagementUserDetailsRoute:
      ProponentProponentLayoutUserManagementUserDetailsRoute,
    ProponentProponentLayoutProjectsIndexRoute:
      ProponentProponentLayoutProjectsIndexRoute,
    ProponentProponentLayoutUserManagementIndexRoute:
      ProponentProponentLayoutUserManagementIndexRoute,
    ProponentProponentLayoutProjectsProjectIdRoute:
      ProponentProponentLayoutProjectsProjectIdRouteWithChildren,
  }

const ProponentProponentLayoutRouteWithChildren =
  ProponentProponentLayoutRoute._addFileChildren(
    ProponentProponentLayoutRouteChildren,
  )

interface ProponentRouteChildren {
  ProponentProponentLayoutRoute: typeof ProponentProponentLayoutRouteWithChildren
  ProponentRegistrationCompleteRoute: typeof ProponentRegistrationCompleteRoute
  ProponentRegistrationCreateAccountRoute: typeof ProponentRegistrationCreateAccountRoute
  ProponentRegistrationIndexRoute: typeof ProponentRegistrationIndexRoute
}

const ProponentRouteChildren: ProponentRouteChildren = {
  ProponentProponentLayoutRoute: ProponentProponentLayoutRouteWithChildren,
  ProponentRegistrationCompleteRoute: ProponentRegistrationCompleteRoute,
  ProponentRegistrationCreateAccountRoute:
    ProponentRegistrationCreateAccountRoute,
  ProponentRegistrationIndexRoute: ProponentRegistrationIndexRoute,
}

const ProponentRouteWithChildren = ProponentRoute._addFileChildren(
  ProponentRouteChildren,
)

interface StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren {
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
}

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren: StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren =
  {
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute,
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute,
  }

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute._addFileChildren(
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteChildren,
  )

interface StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren {
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
}

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren: StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren =
  {
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren,
  }

const StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren =
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute._addFileChildren(
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteChildren,
  )

interface StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren {
  StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren
}

const StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren: StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren =
  {
    StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute,
    StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren,
  }

const StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren =
  StaffStaffLayoutProjectsProjectIdProjectLayoutRoute._addFileChildren(
    StaffStaffLayoutProjectsProjectIdProjectLayoutRouteChildren,
  )

interface StaffStaffLayoutProjectsProjectIdRouteChildren {
  StaffStaffLayoutProjectsProjectIdProjectLayoutRoute: typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren
}

const StaffStaffLayoutProjectsProjectIdRouteChildren: StaffStaffLayoutProjectsProjectIdRouteChildren =
  {
    StaffStaffLayoutProjectsProjectIdProjectLayoutRoute:
      StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren,
  }

const StaffStaffLayoutProjectsProjectIdRouteWithChildren =
  StaffStaffLayoutProjectsProjectIdRoute._addFileChildren(
    StaffStaffLayoutProjectsProjectIdRouteChildren,
  )

interface StaffStaffLayoutRouteChildren {
  StaffStaffLayoutDocumentsIndexRoute: typeof StaffStaffLayoutDocumentsIndexRoute
  StaffStaffLayoutInvitationsIndexRoute: typeof StaffStaffLayoutInvitationsIndexRoute
  StaffStaffLayoutProjectsIndexRoute: typeof StaffStaffLayoutProjectsIndexRoute
  StaffStaffLayoutInvitationsEntitiesProponentIdRoute: typeof StaffStaffLayoutInvitationsEntitiesProponentIdRoute
  StaffStaffLayoutProjectsProjectIdRoute: typeof StaffStaffLayoutProjectsProjectIdRouteWithChildren
}

const StaffStaffLayoutRouteChildren: StaffStaffLayoutRouteChildren = {
  StaffStaffLayoutDocumentsIndexRoute: StaffStaffLayoutDocumentsIndexRoute,
  StaffStaffLayoutInvitationsIndexRoute: StaffStaffLayoutInvitationsIndexRoute,
  StaffStaffLayoutProjectsIndexRoute: StaffStaffLayoutProjectsIndexRoute,
  StaffStaffLayoutInvitationsEntitiesProponentIdRoute:
    StaffStaffLayoutInvitationsEntitiesProponentIdRoute,
  StaffStaffLayoutProjectsProjectIdRoute:
    StaffStaffLayoutProjectsProjectIdRouteWithChildren,
}

const StaffStaffLayoutRouteWithChildren =
  StaffStaffLayoutRoute._addFileChildren(StaffStaffLayoutRouteChildren)

interface StaffRouteChildren {
  StaffStaffLayoutRoute: typeof StaffStaffLayoutRouteWithChildren
  StaffNoRolesRoute: typeof StaffNoRolesRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffLayoutRoute: StaffStaffLayoutRouteWithChildren,
  StaffNoRolesRoute: StaffNoRolesRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/need-access': typeof NeedAccessRoute
  '/not-found': typeof NotFoundRoute
  '/proponent': typeof ProponentProponentLayoutRouteWithChildren
  '/staff': typeof StaffStaffLayoutRouteWithChildren
  '/staff/no-roles': typeof StaffNoRolesRoute
  '/oidc-callback': typeof OidcCallbackIndexRoute
  '/proponent/profile': typeof ProponentProponentLayoutProfileRoute
  '/proponent/registration/complete': typeof ProponentRegistrationCompleteRoute
  '/proponent/registration/create-account': typeof ProponentRegistrationCreateAccountRoute
  '/proponent/aboutpage': typeof ProponentProponentLayoutAboutpageLazyRoute
  '/proponent/registration': typeof ProponentRegistrationIndexRoute
  '/proponent/user-management/edit-profile': typeof ProponentProponentLayoutUserManagementEditProfileRoute
  '/proponent/user-management/edit-role': typeof ProponentProponentLayoutUserManagementEditRoleRoute
  '/proponent/user-management/new-user': typeof ProponentProponentLayoutUserManagementNewUserRoute
  '/proponent/user-management/profile': typeof ProponentProponentLayoutUserManagementProfileRoute
  '/proponent/user-management/user-details': typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  '/proponent/projects': typeof ProponentProponentLayoutProjectsIndexRoute
  '/proponent/user-management': typeof ProponentProponentLayoutUserManagementIndexRoute
  '/staff/documents': typeof StaffStaffLayoutDocumentsIndexRoute
  '/staff/invitations': typeof StaffStaffLayoutInvitationsIndexRoute
  '/staff/projects': typeof StaffStaffLayoutProjectsIndexRoute
  '/proponent/projects/$projectId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/staff/invitations/entities/$proponentId': typeof StaffStaffLayoutInvitationsEntitiesProponentIdRoute
  '/staff/projects/$projectId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/proponent/projects/$projectId/new-submission': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  '/proponent/projects/$projectId/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/staff/projects/$projectId/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/staff/projects/$projectId/submission-packages/$submissionPackageId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/need-access': typeof NeedAccessRoute
  '/not-found': typeof NotFoundRoute
  '/proponent': typeof ProponentProponentLayoutRouteWithChildren
  '/staff': typeof StaffStaffLayoutRouteWithChildren
  '/staff/no-roles': typeof StaffNoRolesRoute
  '/oidc-callback': typeof OidcCallbackIndexRoute
  '/proponent/profile': typeof ProponentProponentLayoutProfileRoute
  '/proponent/registration/complete': typeof ProponentRegistrationCompleteRoute
  '/proponent/registration/create-account': typeof ProponentRegistrationCreateAccountRoute
  '/proponent/aboutpage': typeof ProponentProponentLayoutAboutpageLazyRoute
  '/proponent/registration': typeof ProponentRegistrationIndexRoute
  '/proponent/user-management/edit-profile': typeof ProponentProponentLayoutUserManagementEditProfileRoute
  '/proponent/user-management/edit-role': typeof ProponentProponentLayoutUserManagementEditRoleRoute
  '/proponent/user-management/new-user': typeof ProponentProponentLayoutUserManagementNewUserRoute
  '/proponent/user-management/profile': typeof ProponentProponentLayoutUserManagementProfileRoute
  '/proponent/user-management/user-details': typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  '/proponent/projects': typeof ProponentProponentLayoutProjectsIndexRoute
  '/proponent/user-management': typeof ProponentProponentLayoutUserManagementIndexRoute
  '/staff/documents': typeof StaffStaffLayoutDocumentsIndexRoute
  '/staff/invitations': typeof StaffStaffLayoutInvitationsIndexRoute
  '/staff/projects': typeof StaffStaffLayoutProjectsIndexRoute
  '/proponent/projects/$projectId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/staff/invitations/entities/$proponentId': typeof StaffStaffLayoutInvitationsEntitiesProponentIdRoute
  '/staff/projects/$projectId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/proponent/projects/$projectId/new-submission': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/need-access': typeof NeedAccessRoute
  '/not-found': typeof NotFoundRoute
  '/proponent': typeof ProponentRouteWithChildren
  '/proponent/_proponentLayout': typeof ProponentProponentLayoutRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/staff/_staffLayout': typeof StaffStaffLayoutRouteWithChildren
  '/staff/no-roles': typeof StaffNoRolesRoute
  '/oidc-callback/': typeof OidcCallbackIndexRoute
  '/proponent/_proponentLayout/profile': typeof ProponentProponentLayoutProfileRoute
  '/proponent/registration/complete': typeof ProponentRegistrationCompleteRoute
  '/proponent/registration/create-account': typeof ProponentRegistrationCreateAccountRoute
  '/proponent/_proponentLayout/aboutpage': typeof ProponentProponentLayoutAboutpageLazyRoute
  '/proponent/registration/': typeof ProponentRegistrationIndexRoute
  '/proponent/_proponentLayout/user-management/edit-profile': typeof ProponentProponentLayoutUserManagementEditProfileRoute
  '/proponent/_proponentLayout/user-management/edit-role': typeof ProponentProponentLayoutUserManagementEditRoleRoute
  '/proponent/_proponentLayout/user-management/new-user': typeof ProponentProponentLayoutUserManagementNewUserRoute
  '/proponent/_proponentLayout/user-management/profile': typeof ProponentProponentLayoutUserManagementProfileRoute
  '/proponent/_proponentLayout/user-management/user-details': typeof ProponentProponentLayoutUserManagementUserDetailsRoute
  '/proponent/_proponentLayout/projects/': typeof ProponentProponentLayoutProjectsIndexRoute
  '/proponent/_proponentLayout/user-management/': typeof ProponentProponentLayoutUserManagementIndexRoute
  '/staff/_staffLayout/documents/': typeof StaffStaffLayoutDocumentsIndexRoute
  '/staff/_staffLayout/invitations/': typeof StaffStaffLayoutInvitationsIndexRoute
  '/staff/_staffLayout/projects/': typeof StaffStaffLayoutProjectsIndexRoute
  '/proponent/_proponentLayout/projects/$projectId': typeof ProponentProponentLayoutProjectsProjectIdRouteWithChildren
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/staff/_staffLayout/invitations/entities/$proponentId': typeof StaffStaffLayoutInvitationsEntitiesProponentIdRoute
  '/staff/_staffLayout/projects/$projectId': typeof StaffStaffLayoutProjectsProjectIdRouteWithChildren
  '/staff/_staffLayout/projects/$projectId/_projectLayout': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutRouteWithChildren
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutNewSubmissionRoute
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/staff/_staffLayout/projects/$projectId/_projectLayout/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutIndexRoute
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdRouteWithChildren
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutRouteWithChildren
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutIndexRoute
  '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': typeof ProponentProponentLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
  '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId': typeof StaffStaffLayoutProjectsProjectIdProjectLayoutSubmissionPackagesSubmissionPackageIdSubmissionLayoutSubmissionsSubmissionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/need-access'
    | '/not-found'
    | '/proponent'
    | '/staff'
    | '/staff/no-roles'
    | '/oidc-callback'
    | '/proponent/profile'
    | '/proponent/registration/complete'
    | '/proponent/registration/create-account'
    | '/proponent/aboutpage'
    | '/proponent/registration'
    | '/proponent/user-management/edit-profile'
    | '/proponent/user-management/edit-role'
    | '/proponent/user-management/new-user'
    | '/proponent/user-management/profile'
    | '/proponent/user-management/user-details'
    | '/proponent/projects'
    | '/proponent/user-management'
    | '/staff/documents'
    | '/staff/invitations'
    | '/staff/projects'
    | '/proponent/projects/$projectId'
    | '/staff/invitations/entities/$proponentId'
    | '/staff/projects/$projectId'
    | '/proponent/projects/$projectId/new-submission'
    | '/proponent/projects/$projectId/'
    | '/staff/projects/$projectId/'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId/'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/need-access'
    | '/not-found'
    | '/proponent'
    | '/staff'
    | '/staff/no-roles'
    | '/oidc-callback'
    | '/proponent/profile'
    | '/proponent/registration/complete'
    | '/proponent/registration/create-account'
    | '/proponent/aboutpage'
    | '/proponent/registration'
    | '/proponent/user-management/edit-profile'
    | '/proponent/user-management/edit-role'
    | '/proponent/user-management/new-user'
    | '/proponent/user-management/profile'
    | '/proponent/user-management/user-details'
    | '/proponent/projects'
    | '/proponent/user-management'
    | '/staff/documents'
    | '/staff/invitations'
    | '/staff/projects'
    | '/proponent/projects/$projectId'
    | '/staff/invitations/entities/$proponentId'
    | '/staff/projects/$projectId'
    | '/proponent/projects/$projectId/new-submission'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId'
    | '/proponent/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
    | '/staff/projects/$projectId/submission-packages/$submissionPackageId/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/login'
    | '/logout'
    | '/need-access'
    | '/not-found'
    | '/proponent'
    | '/proponent/_proponentLayout'
    | '/staff'
    | '/staff/_staffLayout'
    | '/staff/no-roles'
    | '/oidc-callback/'
    | '/proponent/_proponentLayout/profile'
    | '/proponent/registration/complete'
    | '/proponent/registration/create-account'
    | '/proponent/_proponentLayout/aboutpage'
    | '/proponent/registration/'
    | '/proponent/_proponentLayout/user-management/edit-profile'
    | '/proponent/_proponentLayout/user-management/edit-role'
    | '/proponent/_proponentLayout/user-management/new-user'
    | '/proponent/_proponentLayout/user-management/profile'
    | '/proponent/_proponentLayout/user-management/user-details'
    | '/proponent/_proponentLayout/projects/'
    | '/proponent/_proponentLayout/user-management/'
    | '/staff/_staffLayout/documents/'
    | '/staff/_staffLayout/invitations/'
    | '/staff/_staffLayout/projects/'
    | '/proponent/_proponentLayout/projects/$projectId'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout'
    | '/staff/_staffLayout/invitations/entities/$proponentId'
    | '/staff/_staffLayout/projects/$projectId'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/'
    | '/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
    | '/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NeedAccessRoute: typeof NeedAccessRoute
  NotFoundRoute: typeof NotFoundRoute
  ProponentRoute: typeof ProponentRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  OidcCallbackIndexRoute: typeof OidcCallbackIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NeedAccessRoute: NeedAccessRoute,
  NotFoundRoute: NotFoundRoute,
  ProponentRoute: ProponentRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  OidcCallbackIndexRoute: OidcCallbackIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/error",
        "/login",
        "/logout",
        "/need-access",
        "/not-found",
        "/proponent",
        "/staff",
        "/oidc-callback/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/need-access": {
      "filePath": "need-access.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    },
    "/proponent": {
      "filePath": "proponent",
      "children": [
        "/proponent/_proponentLayout",
        "/proponent/registration/complete",
        "/proponent/registration/create-account",
        "/proponent/registration/"
      ]
    },
    "/proponent/_proponentLayout": {
      "filePath": "proponent/_proponentLayout.tsx",
      "parent": "/proponent",
      "children": [
        "/proponent/_proponentLayout/profile",
        "/proponent/_proponentLayout/aboutpage",
        "/proponent/_proponentLayout/user-management/edit-profile",
        "/proponent/_proponentLayout/user-management/edit-role",
        "/proponent/_proponentLayout/user-management/new-user",
        "/proponent/_proponentLayout/user-management/profile",
        "/proponent/_proponentLayout/user-management/user-details",
        "/proponent/_proponentLayout/projects/",
        "/proponent/_proponentLayout/user-management/",
        "/proponent/_proponentLayout/projects/$projectId"
      ]
    },
    "/staff": {
      "filePath": "staff",
      "children": [
        "/staff/_staffLayout",
        "/staff/no-roles"
      ]
    },
    "/staff/_staffLayout": {
      "filePath": "staff/_staffLayout.tsx",
      "parent": "/staff",
      "children": [
        "/staff/_staffLayout/documents/",
        "/staff/_staffLayout/invitations/",
        "/staff/_staffLayout/projects/",
        "/staff/_staffLayout/invitations/entities/$proponentId",
        "/staff/_staffLayout/projects/$projectId"
      ]
    },
    "/staff/no-roles": {
      "filePath": "staff/no-roles.tsx",
      "parent": "/staff"
    },
    "/oidc-callback/": {
      "filePath": "oidc-callback/index.tsx"
    },
    "/proponent/_proponentLayout/profile": {
      "filePath": "proponent/_proponentLayout/profile.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/registration/complete": {
      "filePath": "proponent/registration/complete.tsx",
      "parent": "/proponent"
    },
    "/proponent/registration/create-account": {
      "filePath": "proponent/registration/create-account.tsx",
      "parent": "/proponent"
    },
    "/proponent/_proponentLayout/aboutpage": {
      "filePath": "proponent/_proponentLayout/aboutpage.lazy.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/registration/": {
      "filePath": "proponent/registration/index.tsx",
      "parent": "/proponent"
    },
    "/proponent/_proponentLayout/user-management/edit-profile": {
      "filePath": "proponent/_proponentLayout/user-management/edit-profile.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/_proponentLayout/user-management/edit-role": {
      "filePath": "proponent/_proponentLayout/user-management/edit-role.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/_proponentLayout/user-management/new-user": {
      "filePath": "proponent/_proponentLayout/user-management/new-user.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/_proponentLayout/user-management/profile": {
      "filePath": "proponent/_proponentLayout/user-management/profile.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/_proponentLayout/user-management/user-details": {
      "filePath": "proponent/_proponentLayout/user-management/user-details.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/_proponentLayout/projects/": {
      "filePath": "proponent/_proponentLayout/projects/index.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/proponent/_proponentLayout/user-management/": {
      "filePath": "proponent/_proponentLayout/user-management/index.tsx",
      "parent": "/proponent/_proponentLayout"
    },
    "/staff/_staffLayout/documents/": {
      "filePath": "staff/_staffLayout/documents/index.tsx",
      "parent": "/staff/_staffLayout"
    },
    "/staff/_staffLayout/invitations/": {
      "filePath": "staff/_staffLayout/invitations/index.tsx",
      "parent": "/staff/_staffLayout"
    },
    "/staff/_staffLayout/projects/": {
      "filePath": "staff/_staffLayout/projects/index.tsx",
      "parent": "/staff/_staffLayout"
    },
    "/proponent/_proponentLayout/projects/$projectId": {
      "filePath": "proponent/_proponentLayout/projects/$projectId",
      "parent": "/proponent/_proponentLayout",
      "children": [
        "/proponent/_proponentLayout/projects/$projectId/_projectLayout"
      ]
    },
    "/proponent/_proponentLayout/projects/$projectId/_projectLayout": {
      "filePath": "proponent/_proponentLayout/projects/$projectId/_projectLayout.tsx",
      "parent": "/proponent/_proponentLayout/projects/$projectId",
      "children": [
        "/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission",
        "/proponent/_proponentLayout/projects/$projectId/_projectLayout/",
        "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId"
      ]
    },
    "/staff/_staffLayout/invitations/entities/$proponentId": {
      "filePath": "staff/_staffLayout/invitations/entities/$proponentId.tsx",
      "parent": "/staff/_staffLayout"
    },
    "/staff/_staffLayout/projects/$projectId": {
      "filePath": "staff/_staffLayout/projects/$projectId",
      "parent": "/staff/_staffLayout",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout"
      ]
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout/",
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId"
      ]
    },
    "/proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission": {
      "filePath": "proponent/_proponentLayout/projects/$projectId/_projectLayout/new-submission.tsx",
      "parent": "/proponent/_proponentLayout/projects/$projectId/_projectLayout"
    },
    "/proponent/_proponentLayout/projects/$projectId/_projectLayout/": {
      "filePath": "proponent/_proponentLayout/projects/$projectId/_projectLayout/index.tsx",
      "parent": "/proponent/_proponentLayout/projects/$projectId/_projectLayout"
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/index.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout"
    },
    "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId": {
      "filePath": "proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "parent": "/proponent/_proponentLayout/projects/$projectId/_projectLayout",
      "children": [
        "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
      ]
    },
    "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout": {
      "filePath": "proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout.tsx",
      "parent": "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "children": [
        "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/",
        "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId"
      ]
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
      ]
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId",
      "children": [
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/",
        "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId"
      ]
    },
    "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/": {
      "filePath": "proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index.tsx",
      "parent": "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/index.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId": {
      "filePath": "proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId.tsx",
      "parent": "/proponent/_proponentLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    },
    "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId": {
      "filePath": "staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout/submissions/$submissionId.tsx",
      "parent": "/staff/_staffLayout/projects/$projectId/_projectLayout/submission-packages/$submissionPackageId/_submissionLayout"
    }
  }
}
ROUTE_MANIFEST_END */
