name: Update Changelog on Push to Main

on:
  push:
    branches:
      - develop

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to access full commit history

      - name: Update Changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: CHANGELOG.md
          skip-version-file: true
          skip-commit: false
          tag-prefix: ""
  
